inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'db/**/*.rb'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - app/controllers/application_controller.rb

# Controlling flow w/ guard clauses can be overly clever and makes code harder to read - ABW
Style/GuardClause:
  Enabled: false
