version: "3.6"

services:
  web:
    build: .
    environment:
      SINAIID_UCLA_KEY: 'abc123'
      SINAIID_URL: '/mock-sinai'
      DOMAIN: 'localhost:3030'
    env_file:
      - ./default.env
      - ./docker.env
    ports:
      - "3030:3000"
    volumes:
      - .:/app
      - bundle_dir:/usr/local/bundle
    working_dir: /app
    command: ["sh", "/app/docker/start-app.sh"]

  # db:
  #   image: mysql:5.6
  #   volumes:
  #     - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  #     - ./docker/conf.d:/etc/mysql/conf.d
  #     - mysql_data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  bundle_dir:
